import type { DbEnvironment, Reversibility, Severity } from "./types";

/**
 * The safety-verdict PR comment (PR3, doc 11 §5). Pure and deterministic —
 * the same report input always renders the same markdown, and the leading
 * HTML marker lets the poster UPDATE the existing comment instead of
 * stacking a new one per re-post.
 */

export const VERDICT_MARKER = "<!-- sentinel-verdict -->";

export interface VerdictFinding {
  statement: string;
  severity: Severity;
  note?: string | null;
}

export interface VerdictReportInput {
  requestId: string;
  title: string;
  severity: Severity;
  environment?: DbEnvironment;
  rollbackVerified: boolean;
  reversibility: Reversibility;
  rowsAffected?: number | null;
  findings: VerdictFinding[];
  qodo: { verdict: string; findings: string[] };
  /** Link back to the approval console for this request. */
  consoleUrl?: string;
}

const SEV_ICON: Record<Severity, string> = { green: "🟢", amber: "🟠", red: "🔴" };

export function buildVerdictComment(input: VerdictReportInput): string {
  const lines: string[] = [];
  lines.push(VERDICT_MARKER);
  lines.push(`## ${SEV_ICON[input.severity]} Migration Sentinel — safety verdict: ${input.severity.toUpperCase()}`);
  lines.push("");
  lines.push(`**${input.title}**` + (input.environment ? ` · target environment: \`${input.environment}\`` : ""));
  lines.push("");
  lines.push("| Check | Result |");
  lines.push("|---|---|");
  lines.push(`| Blast severity | ${SEV_ICON[input.severity]} ${input.severity.toUpperCase()} |`);
  lines.push(
    `| Rollback proof | ${
      input.rollbackVerified ? "✅ proven on a shadow database" : "❌ not proven — down migration does not restore state"
    } |`,
  );
  lines.push(`| Reversibility | ${input.reversibility} |`);
  if (input.rowsAffected != null) {
    lines.push(`| Rows affected (est.) | ${input.rowsAffected.toLocaleString("en-US")} |`);
  }
  lines.push(`| Qodo review | ${input.qodo.verdict.replace(/_/g, " ")} |`);
  lines.push("");

  if (input.findings.length > 0) {
    lines.push("### Blast findings");
    for (const f of input.findings) {
      lines.push(`- ${SEV_ICON[f.severity]} \`${f.statement}\`${f.note ? ` — ${f.note}` : ""}`);
    }
    lines.push("");
  }

  if (input.qodo.findings.length > 0) {
    lines.push("### Qodo findings");
    for (const q of input.qodo.findings) lines.push(`- ${q}`);
    lines.push("");
  }

  if (input.consoleUrl) {
    lines.push(`[Review & decide in the Sentinel console →](${input.consoleUrl})`);
    lines.push("");
  }
  lines.push(`<sub>request \`${input.requestId}\` · generated by Migration Sentinel</sub>`);
  return lines.join("\n");
}
